### ISSUE TITLE
oFReactNative/SquareApp.h:3:10: 'ofxiOS.h' file not found

### ISSUE THREAD

**Issue by moebiussurfing** [razvanilin/ofxReactNative#1]
Thanks for the addon @razvanilin . I am interested to test it. 
I am getting this error:

Showing All Issues
../of_v0.9.8_ios_release/apps/oFReactNative/ios/oFReactNative/SquareApp.h:3:10: 'ofxiOS.h' file not found

Should I add the addon? I didn't made the rename thing on the readme, I assume this is for new projects...

**Comment by razvanilin** [comment]
@moebiussurfing Can't say for sure now what's the issue, but I'll give it a try when I get in the office tomorrow. The ofxiOS addon should be included already in the project so make sure it's linked properly

**Comment by razvanilin** [comment]
@moebiussurfing I checked it now and removed some unnecessary references that were in the project 83e379b2c74962ae22a1079ee9d747ed492d07c8 . Although that didn't seem to be the problem you were having. Make sure you put this project into the `myapps` folder. Also make sure you got the `of` version for ios. http://openframeworks.cc/versions/v0.9.8/of_v0.9.8_ios_release.zip

Let me know if you managed to get it running and I'll close this issue

**Comment by moebiussurfing** [comment]
thanks @razvanilin ! it worked now. I think the problem was I used the folder of/apps instead.
